services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PESQUISADOR_URL: ${NEXT_PUBLIC_PESQUISADOR_URL}
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
